import { ChevronRight, Landmark, BookOpen, Terminal, Download } from 'lucide-react';
import { useState } from 'react';
import { motion, AnimatePresence } from 'motion/react';

interface SkillDetail {
  id: string;
  type: 'MAIN SKILL' | 'SUB SKILL';
  title: string;
  summary: string;
  whenToUse: string;
  methodProgram: string;
  executionSkeleton: string[];
  patternFlow: string;
}

const SKILL_DETAILS: Record<string, SkillDetail> = {
  'Labor Theory Implementation': {
    id: '#SC-01',
    type: 'MAIN SKILL',
    title: 'Systemic Crisis Analysis',
    summary: 'A method for analyzing the decline or transformation of complex socio-political systems by tracing how their core principles, when successfully implemented, generate internal contradictions that lead to systemic crisis.',
    whenToUse: 'Use this method to explain how successful ideologies or systems produce their own decline. First identify a system experiencing crisis or transformation. Then trace how its foundational principles, through historical implementation, created psychological, intellectual, or institutional contradictions that undermined the system from within.',
    methodProgram: 'First establish the original principles or civilizational ideal that serves as the evaluative baseline. Then trace the historical development path of implementing these principles, documenting their social, economic, and intellectual outcomes. Next, identify how this very success generated internal contradictions, psychological shifts, or conceptual reinterpretations that undermined the original framework. Diagnose these contradictions as the causal mechanism producing the observed systemic crisis or ideological reversal. Finally, connect this internal failure process to specific historical outcomes, demonstrating how the system\'s achievements contained the seeds of its own decline.',
    executionSkeleton: [
      'Establish the original principles or evaluative baseline of the system or ideology under analysis',
      'Trace the historical development path and outcomes of implementing these principles',
      'Identify the internal contradictions, reinterpretations, or psychological shifts generated by prior success',
      'Diagnose how these contradictions lead to observed crises, deviations, or fundamental reversals',
      'Connect the internal failure mechanism to specific historical outcomes or intellectual transformations'
    ],
    patternFlow: 'Baseline Establishment → Historical Trajectory → Contradiction Identification → Crisis Diagnosis → Outcome Connection'
  },
  'Supply-Side Equilibrium': {
    id: '#SE-02',
    type: 'MAIN SKILL',
    title: 'Supply-Side Equilibrium',
    summary: 'A framework for maintaining market stability by prioritizing production capacity and supply-side incentives.',
    whenToUse: 'Apply when analyzing long-term economic growth or addressing stagnation in production-heavy economies.',
    methodProgram: 'Identify production bottlenecks and regulatory constraints. Implement incentives for capital investment and technological innovation. Monitor aggregate supply levels to ensure market clearing.',
    executionSkeleton: [
      'Assess current production capacity and constraints',
      'Identify key supply-side variables and incentives',
      'Model the impact of increased output on aggregate demand',
      'Execute policy adjustments to favor production',
      'Monitor market clearing and price stability'
    ],
    patternFlow: 'Capacity Assessment → Incentive Identification → Supply Modeling → Policy Execution → Stability Monitoring'
  },
  'Capital Accumulation': {
    id: '#CA-03',
    type: 'MAIN SKILL',
    title: 'Capital Accumulation',
    summary: 'A recursive logic for growth driven by the continuous reinvestment of surplus value into productive assets.',
    whenToUse: 'Use to model the expansion of industrial systems or the concentration of wealth in capital-intensive sectors.',
    methodProgram: 'Calculate the rate of surplus value extraction. Determine the ratio of reinvestment versus consumption. Track the organic composition of capital over time to predict profitability trends.',
    executionSkeleton: [
      'Determine the current rate of surplus value',
      'Set reinvestment targets for productive capital',
      'Monitor the changing ratio of constant to variable capital',
      'Analyze the impact on the general rate of profit',
      'Adjust accumulation strategies to counter falling profit rates'
    ],
    patternFlow: 'Surplus Calculation → Reinvestment Targeting → Composition Monitoring → Profit Analysis → Strategy Adjustment'
  },
  'Moral Sentiments Filter': {
    id: '#MS-04',
    type: 'SUB SKILL',
    title: 'Moral Sentiments Filter',
    summary: 'An ethical heuristic that evaluates economic actions through the perspective of an impartial, sympathetic observer.',
    whenToUse: 'Apply to ensure that market-driven decisions do not undermine social cohesion or violate fundamental ethical norms.',
    methodProgram: 'Invoke the "Impartial Spectator" module. Assess the sympathy co-efficients of all stakeholders involved. Reject or modify actions that cause unmerited distress or social fragmentation.',
    executionSkeleton: [
      'Define the economic action or policy under review',
      'Simulate the perspective of the Impartial Spectator',
      'Calculate the social sympathy and distress indices',
      'Identify ethical contradictions or social risks',
      'Synthesize a socially cohesive alternative'
    ],
    patternFlow: 'Action Definition → Perspective Simulation → Sympathy Calculation → Risk Identification → Cohesive Synthesis'
  },
  'Ethical Utility Logic': {
    id: '#EU-05',
    type: 'SUB SKILL',
    title: 'Ethical Utility Logic',
    summary: 'A calculus for optimizing societal well-being by weighting individual pleasures against long-term qualitative happiness.',
    whenToUse: 'Use when balancing competing interests in public policy or large-scale social engineering projects.',
    methodProgram: 'Perform a comprehensive felicific calculus. Apply qualitative weights to different types of utility. Optimize for the greatest happiness of the greatest number while maintaining stability.',
    executionSkeleton: [
      'Inventory all impacted parties and their utility functions',
      'Assign qualitative weights to pleasure and pain indices',
      'Aggregate the total societal utility score',
      'Evaluate the long-term stability implications',
      'Select the option that maximizes weighted happiness'
    ],
    patternFlow: 'Utility Inventory → Qualitative Weighting → Aggregate Calculation → Stability Evaluation → Happiness Optimization'
  },
  'Dialectical Synthesis': {
    id: '#DS-06',
    type: 'SUB SKILL',
    title: 'Dialectical Synthesis',
    summary: 'A logical process for resolving theoretical conflicts by merging opposing ideas into a higher, more comprehensive unity.',
    whenToUse: 'Apply when faced with seemingly irreconcilable economic or social contradictions.',
    methodProgram: 'Identify the prevailing thesis and its emerging antithesis. Extract the "rational kernel" from both positions. Construct a sublated synthesis that preserves the truths of both while discarding errors.',
    executionSkeleton: [
      'Define the current theoretical thesis',
      'Identify the emerging contradictions and antithesis',
      'Analyze the core rational elements of both positions',
      'Construct a higher-level synthesis (Aufhebung)',
      'Validate the synthesis against historical and empirical data'
    ],
    patternFlow: 'Thesis Definition → Antithesis Identification → Rational Extraction → Synthesis Construction → Validation'
  }
};

interface MethodologyViewProps {
  selectedEconomist: string;
}

export default function MethodologyView({ selectedEconomist }: MethodologyViewProps) {
  const [selectedSkill, setSelectedSkill] = useState<string>('Labor Theory Implementation');
  const [generatedAuthors, setGeneratedAuthors] = useState<Set<string>>(new Set());
  
  const isGenerated = generatedAuthors.has(selectedEconomist);
  const detail = SKILL_DETAILS[selectedSkill];

  const handleGenerate = () => {
    setGeneratedAuthors(prev => new Set(prev).add(selectedEconomist));
  };

  return (
    <div className="flex-grow bg-background p-8 lg:p-12 overflow-y-auto custom-scrollbar">
      {/* Header Section */}
      <section className="mb-16">
        <div className="flex flex-col md:flex-row md:items-end justify-between gap-8">
          <div className="space-y-4">
            <nav className="text-[10px] uppercase tracking-widest text-secondary font-bold mb-2 flex items-center gap-2">
              <span>Methodology</span> <ChevronRight className="w-2.5 h-2.5" />
              <span className="text-primary">{selectedEconomist}</span>
            </nav>
            <h1 className="text-5xl lg:text-6xl font-headline font-medium text-on-background leading-tight">
              Methodology & Intellectual Frameworks
            </h1>
            <p className="text-secondary max-w-2xl text-lg font-body leading-relaxed">
              Exploring the dialectical structures and cognitive heuristics that govern the Lexicon's synthesis of classical and modern economic theory.
            </p>
          </div>
        </div>
      </section>

      {/* Skills Section Header */}
      <section className="flex justify-between items-center mb-8">
        <h2 className="text-xs font-label text-primary uppercase tracking-[0.2em]">Core Theoretical Competencies</h2>
        {!isGenerated && (
          <button 
            onClick={handleGenerate}
            className="bg-primary text-on-primary px-6 py-2 rounded-sm font-label text-xs tracking-widest uppercase hover:bg-primary-dim transition-all shadow-md"
          >
            Generate All Skills
          </button>
        )}
      </section>

      {/* Main Skills Bento Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">
        {/* Left Column */}
        <div className={`space-y-8 ${isGenerated ? 'lg:col-span-7' : 'lg:col-span-12'}`}>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
            {/* Main Skills */}
            <div className="bg-surface-container-low p-6 transition-all hover:bg-surface-container-high rounded-sm editorial-shadow">
              <div className="flex justify-between items-start mb-6">
                <div>
                  <span className="text-[10px] font-label text-primary uppercase tracking-widest block mb-2">Core Pillar 01</span>
                  <h3 className="text-xl font-headline font-semibold">Main Skills</h3>
                </div>
                <Landmark className="w-5 h-5 text-primary" />
              </div>
              
              {isGenerated ? (
                <div className="space-y-3">
                  {[
                    { title: 'Labor Theory Implementation', subtitle: 'Objective Value Anchoring' },
                    { title: 'Supply-Side Equilibrium', subtitle: 'Say’s Law Parity' },
                    { title: 'Capital Accumulation', subtitle: 'Recursive Growth Loop' },
                  ].map((skill, i) => (
                    <button
                      key={i}
                      onClick={() => setSelectedSkill(skill.title)}
                      className={`w-full group flex items-center justify-between p-4 bg-white shadow-sm hover:shadow-md transition-all text-left rounded-sm h-20 ${
                        selectedSkill === skill.title ? 'border-l-4 border-primary' : ''
                      }`}
                    >
                      <div>
                        <h4 className={`font-headline text-base group-hover:text-primary transition-colors ${selectedSkill === skill.title ? 'text-primary' : ''}`}>
                          {skill.title}
                        </h4>
                      </div>
                      <ChevronRight className={`w-4 h-4 transition-all ${selectedSkill === skill.title ? 'text-primary translate-x-1' : 'text-outline-variant group-hover:text-primary'}`} />
                    </button>
                  ))}
                </div>
              ) : (
                <div className="py-12 px-6 text-center border-2 border-dashed border-outline-variant/10 rounded-sm">
                  <p className="text-sm text-secondary italic font-body">
                    Skills have not been extracted for this author.
                  </p>
                </div>
              )}
            </div>

            {/* Sub Skills */}
            <div className="bg-surface-container-low p-6 transition-all hover:bg-surface-container-high rounded-sm editorial-shadow">
              <div className="flex justify-between items-start mb-6">
                <div>
                  <span className="text-[10px] font-label text-primary uppercase tracking-widest block mb-2">Core Pillar 02</span>
                  <h3 className="text-xl font-headline font-semibold">Sub Skills</h3>
                </div>
                <BookOpen className="w-5 h-5 text-primary" />
              </div>
              
              {isGenerated ? (
                <div className="space-y-3">
                  {[
                    { title: 'Moral Sentiments Filter', subtitle: 'Impartial Spectator Proxy' },
                    { title: 'Ethical Utility Logic', subtitle: 'Benevolence Co-efficient' },
                    { title: 'Dialectical Synthesis', subtitle: 'Conflict Resolution Heuristic' },
                  ].map((skill, i) => (
                    <button
                      key={i}
                      onClick={() => setSelectedSkill(skill.title)}
                      className={`w-full group flex items-center justify-between p-4 bg-white shadow-sm hover:shadow-md transition-all text-left rounded-sm h-20 ${
                        selectedSkill === skill.title ? 'border-l-4 border-primary' : ''
                      }`}
                    >
                      <div>
                        <h4 className={`font-headline text-base group-hover:text-primary transition-colors ${selectedSkill === skill.title ? 'text-primary' : ''}`}>
                          {skill.title}
                        </h4>
                      </div>
                      <ChevronRight className={`w-4 h-4 transition-all ${selectedSkill === skill.title ? 'text-primary translate-x-1' : 'text-outline-variant group-hover:text-primary'}`} />
                    </button>
                  ))}
                </div>
              ) : (
                <div className="py-12 px-6 text-center border-2 border-dashed border-outline-variant/10 rounded-sm">
                  <p className="text-sm text-secondary italic font-body">
                    Secondary cognitive heuristics will be populated upon generation.
                  </p>
                </div>
              )}
            </div>
          </div>

          {/* Framework Evolution Analysis */}
          <div className="p-8 bg-on-background text-background flex flex-col md:flex-row items-center justify-between gap-6 rounded-sm editorial-shadow">
            <div className="max-w-4xl text-center md:text-left">
              <h4 className="font-headline text-xl mb-2">Framework Evolution Analysis</h4>
              <p className="text-outline-variant text-sm font-body leading-relaxed">
                The AI models are currently transitioning to the 'Neo-Physiocratic' phase, emphasizing the land-labor-output nexus in digital economies.
              </p>
            </div>
            <button className="bg-primary-container text-on-primary-container px-6 py-3 font-label text-xs uppercase tracking-widest hover:brightness-105 transition-all rounded-sm shrink-0">
              View Roadmap
            </button>
          </div>
        </div>

        {/* Right Column: Detail View */}
        {isGenerated && (
          <div className="lg:col-span-5 sticky top-32 space-y-6">
            <AnimatePresence mode="wait">
              <motion.div
                key={selectedSkill}
                initial={{ opacity: 0, x: 20 }}
                animate={{ opacity: 1, x: 0 }}
                exit={{ opacity: 0, x: -20 }}
                transition={{ duration: 0.3 }}
                className="bg-white shadow-2xl p-8 max-h-[calc(100vh-12rem)] border-t-4 border-primary rounded-sm overflow-y-auto relative custom-scrollbar"
              >
                {/* Background ID Watermark */}
                <div className="absolute top-4 right-4 text-[40px] font-mono font-bold text-primary/5 select-none pointer-events-none">
                  {detail.id}
                </div>

                <div className="flex items-center gap-4 mb-10">
                  <div className="w-12 h-12 bg-primary/10 flex items-center justify-center rounded-sm">
                    <Terminal className="w-6 h-6 text-primary" />
                  </div>
                  <div>
                    <h3 className="font-headline text-2xl font-bold text-on-background">{detail.title}</h3>
                    <p className="text-[10px] font-label text-primary tracking-[0.2em] uppercase font-bold">{detail.type}</p>
                  </div>
                </div>

                <div className="space-y-10">
                  {/* Skill Summary */}
                  <section>
                    <h4 className="text-[10px] font-label text-primary uppercase tracking-[0.2em] font-bold mb-4 flex items-center gap-2">
                      <div className="w-1 h-1 bg-primary rounded-full" /> Skill Summary
                    </h4>
                    <p className="text-lg font-headline font-medium text-on-background leading-relaxed italic border-l-2 border-primary/20 pl-6 py-1">
                      "{detail.summary}"
                    </p>
                  </section>

                  {/* When to Use */}
                  <section className="bg-surface-container-low p-6 rounded-sm border-l-4 border-primary/30 relative overflow-hidden">
                    <div className="absolute top-0 right-0 w-16 h-16 bg-primary/5 rounded-bl-full" />
                    <h4 className="text-[10px] font-label text-primary uppercase tracking-[0.2em] font-bold mb-3">When to Use</h4>
                    <p className="text-sm font-body text-secondary leading-relaxed relative z-10">
                      {detail.whenToUse}
                    </p>
                  </section>

                  {/* Method Program */}
                  <section>
                    <h4 className="text-[10px] font-label text-primary uppercase tracking-[0.2em] font-bold mb-4 flex items-center gap-2">
                      <div className="w-1 h-1 bg-primary rounded-full" /> Method Program
                    </h4>
                    <p className="text-sm font-body text-on-surface-variant leading-relaxed bg-surface-container-high/30 p-6 rounded-sm border border-outline-variant/10">
                      {detail.methodProgram}
                    </p>
                  </section>

                  {/* Execution Skeleton */}
                  <section className="space-y-6">
                    <h4 className="text-[10px] font-label text-primary uppercase tracking-[0.2em] font-bold mb-4">Execution Skeleton</h4>
                    <div className="space-y-4">
                      {detail.executionSkeleton.map((step, idx) => (
                        <div key={idx} className="flex gap-4 items-start group">
                          <span className="font-mono text-[10px] text-primary font-bold bg-primary/10 w-6 h-6 flex items-center justify-center rounded-full shrink-0 group-hover:bg-primary group-hover:text-on-primary transition-all">
                            {idx + 1}
                          </span>
                          <p className="text-sm font-body text-secondary group-hover:text-on-background transition-colors pt-0.5">
                            {step}
                          </p>
                        </div>
                      ))}
                    </div>
                  </section>

                  {/* Pattern Flow */}
                  <section className="pt-8 border-t border-outline-variant/10">
                    <h4 className="text-[10px] font-label text-primary uppercase tracking-[0.2em] font-bold mb-5">Pattern Flow</h4>
                    <div className="flex items-center flex-wrap gap-y-4 gap-x-2">
                      {detail.patternFlow.split(' → ').map((step, idx, arr) => (
                        <div key={idx} className="flex items-center gap-2">
                          <span className="text-[10px] font-label font-bold uppercase tracking-widest bg-on-background text-background px-3 py-1.5 rounded-sm shadow-sm hover:bg-primary transition-colors cursor-default">
                            {step}
                          </span>
                          {idx < arr.length - 1 && <ChevronRight className="w-3 h-3 text-outline-variant" />}
                        </div>
                      ))}
                    </div>
                  </section>

                  {/* Actions */}
                  <div className="pt-6 flex items-center justify-between border-t border-outline-variant/10">
                    <button className="flex items-center gap-2 text-primary font-label text-[10px] uppercase tracking-widest font-bold hover:underline group">
                      <Download className="w-4 h-4" /> Export Methodology
                    </button>
                    <span className="text-[10px] font-mono text-outline-variant">VER: 2.4.0-STABLE</span>
                  </div>
                </div>
              </motion.div>
            </AnimatePresence>
          </div>
        )}
      </div>
    </div>
  );
}
