"""执行渲染阶段，将技能 JSON 转换为主技能与子技能 Markdown。"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass
from typing import Any

DEFAULT_MAIN_SKILL_TYPE = "main_skill"
DEFAULT_SUB_SKILL_TYPE = "sub_skill"

FIXED_USAGE_INSTRUCTIONS = """When answering a question with this skill:

- Follow the Method Program as the primary reasoning path.
- Organize the response according to the Execution Skeleton.
- Treat the first step as the evaluative or conceptual baseline.
- Use the middle steps to trace development, identify contradictions, and diagnose internal failure mechanisms.
- Use the final step to connect the internal mechanism to concrete historical or systemic outcomes.
- Do not merely summarize events; explain how transformation or crisis emerges from the system’s own development.
- If a step requires finer expansion, call an appropriate sub-skill."""

FIXED_OUTPUT_GUIDANCE = """Your response should:

- explain the problem as an endogenous process rather than an external accident
- preserve historical and causal continuity
- emphasize the contrast between original principles and later outcomes
- show how internal contradictions generated by prior success lead to crisis, reversal, or transformation"""


@dataclass(frozen=True)
class MainSkillData:
    """Store validated main-skill JSON fields for markdown rendering."""

    section_id: str
    main_skill_id: str
    name: str
    description: str
    applicability: str
    core_steps: list[str]
    pattern_flow: list[str]
    chapter_method_summary: str
    perspective: str
    perspective_notes: str
    nature: str
    nature_notes: str
    time_orientation: str
    time_orientation_notes: str
    system_scope: str
    system_scope_notes: str
    equilibrium_view: str
    equilibrium_view_notes: str
    logic: list[str]
    logic_notes: str


@dataclass(frozen=True)
class SubSkillData:
    """Store one validated sub-skill item for markdown rendering."""

    section_id: str
    main_skill_id: str
    normalized_pattern: str
    name: str
    description: str
    method_program_summary: str
    method_program_example: str
    abstract_action_chain: list[str]
    source_chunk_ids: list[int]


def _yaml_quote(value: str) -> str:
    """使用 JSON 字符串语法保证 frontmatter 转义安全。"""
    return json.dumps(value, ensure_ascii=False)


def _require_string(value: Any, field_path: str) -> str:
    """Validate required string field and return a trimmed value."""
    if not isinstance(value, str):
        raise ValueError(f"Missing or invalid field: {field_path} (expected string)")
    text = value.strip()
    if not text:
        raise ValueError(f"Missing or invalid field: {field_path} (empty string)")
    return text


def _require_string_list(value: Any, field_path: str) -> list[str]:
    """Validate required list[str] field and return normalized values."""
    if not isinstance(value, list):
        raise ValueError(f"Missing or invalid field: {field_path} (expected list)")
    items: list[str] = []
    for idx, item in enumerate(value):
        if not isinstance(item, str):
            raise ValueError(f"Missing or invalid field: {field_path}[{idx}] (expected string)")
        text = item.strip()
        if not text:
            raise ValueError(f"Missing or invalid field: {field_path}[{idx}] (empty string)")
        items.append(text)
    return items


def _validate_and_normalize_main_skill(raw_skill: dict[str, Any]) -> MainSkillData:
    """Validate strict schema and normalize fields for main-skill rendering."""
    pattern_summary = raw_skill.get("pattern_summary")
    signal_summary = raw_skill.get("signal_summary")
    if not isinstance(pattern_summary, dict):
        raise ValueError("Missing or invalid field: pattern_summary")
    if not isinstance(signal_summary, dict):
        raise ValueError("Missing or invalid field: signal_summary")

    required_pattern_keys = [
        "name",
        "description",
        "applicability",
        "core_steps",
        "pattern_flow",
        "chapter_method_summary",
    ]
    for key in required_pattern_keys:
        if key not in pattern_summary:
            raise ValueError(f"Missing required field: pattern_summary.{key}")

    required_signal_keys = [
        "perspective",
        "nature",
        "time_orientation",
        "system_scope",
        "equilibrium_view",
        "logic",
    ]
    for key in required_signal_keys:
        if key not in signal_summary:
            raise ValueError(f"Missing required field: signal_summary.{key}")

    def read_signal_node(node_key: str) -> tuple[str, str]:
        node = signal_summary.get(node_key)
        if not isinstance(node, dict):
            raise ValueError(f"Missing or invalid field: signal_summary.{node_key}")
        value = _require_string(node.get("value"), f"signal_summary.{node_key}.value")
        notes = _require_string(node.get("notes"), f"signal_summary.{node_key}.notes")
        return value, notes

    logic_node = signal_summary.get("logic")
    if not isinstance(logic_node, dict):
        raise ValueError("Missing or invalid field: signal_summary.logic")
    logic_values = _require_string_list(logic_node.get("value"), "signal_summary.logic.value")
    logic_notes = _require_string(logic_node.get("notes"), "signal_summary.logic.notes")

    perspective, perspective_notes = read_signal_node("perspective")
    nature, nature_notes = read_signal_node("nature")
    time_orientation, time_orientation_notes = read_signal_node("time_orientation")
    system_scope, system_scope_notes = read_signal_node("system_scope")
    equilibrium_view, equilibrium_view_notes = read_signal_node("equilibrium_view")

    return MainSkillData(
        section_id=str(raw_skill.get("section_id", "")).strip(),
        main_skill_id=str(raw_skill.get("main_skill_id", "")).strip(),
        name=_require_string(pattern_summary.get("name"), "pattern_summary.name"),
        description=_require_string(pattern_summary.get("description"), "pattern_summary.description"),
        applicability=_require_string(pattern_summary.get("applicability"), "pattern_summary.applicability"),
        core_steps=_require_string_list(pattern_summary.get("core_steps"), "pattern_summary.core_steps"),
        pattern_flow=_require_string_list(pattern_summary.get("pattern_flow"), "pattern_summary.pattern_flow"),
        chapter_method_summary=_require_string(
            pattern_summary.get("chapter_method_summary"),
            "pattern_summary.chapter_method_summary",
        ),
        perspective=perspective,
        perspective_notes=perspective_notes,
        nature=nature,
        nature_notes=nature_notes,
        time_orientation=time_orientation,
        time_orientation_notes=time_orientation_notes,
        system_scope=system_scope,
        system_scope_notes=system_scope_notes,
        equilibrium_view=equilibrium_view,
        equilibrium_view_notes=equilibrium_view_notes,
        logic=logic_values,
        logic_notes=logic_notes,
    )


def _normalize_pattern_flow(pattern_flow: list[str]) -> str:
    """Render pattern flow into one line; keep single arrow string as-is."""
    if len(pattern_flow) == 1:
        return pattern_flow[0]
    return " -> ".join(pattern_flow)


def _render_main_skill_md(main_skill: dict[str, Any]) -> str:
    """渲染单个主技能 Markdown。"""
    skill = _validate_and_normalize_main_skill(main_skill)

    lines: list[str] = [
        "---",
        f"name: {_yaml_quote(skill.name)}",
        f"type: {_yaml_quote(DEFAULT_MAIN_SKILL_TYPE)}",
        f"description: {_yaml_quote(skill.description)}",
        f"section_id: {_yaml_quote(skill.section_id)}",
        f"main_skill_id: {_yaml_quote(skill.main_skill_id)}",
        f"perspective: {_yaml_quote(skill.perspective)}",
        f"perspective_notes: {_yaml_quote(skill.perspective_notes)}",
        f"nature: {_yaml_quote(skill.nature)}",
        f"nature_notes: {_yaml_quote(skill.nature_notes)}",
        f"time_orientation: {_yaml_quote(skill.time_orientation)}",
        f"time_orientation_notes: {_yaml_quote(skill.time_orientation_notes)}",
        f"system_scope: {_yaml_quote(skill.system_scope)}",
        f"system_scope_notes: {_yaml_quote(skill.system_scope_notes)}",
        f"equilibrium_view: {_yaml_quote(skill.equilibrium_view)}",
        f"equilibrium_view_notes: {_yaml_quote(skill.equilibrium_view_notes)}",
        "logic:",
    ]

    for item in skill.logic:
        lines.append(f"  - {_yaml_quote(item)}")

    lines.extend(
        [
            f"logic_notes: {_yaml_quote(skill.logic_notes)}",
            "---",
            "",
            "# Skill Summary",
            "",
            skill.description,
            "",
            "# When to Use",
            "",
            skill.applicability,
            "",
            "# Method Program",
            "",
            skill.chapter_method_summary,
            "",
            "# Execution Skeleton",
            "",
        ]
    )

    for idx, step in enumerate(skill.core_steps, 1):
        lines.append(f"{idx}. {step}")

    lines.extend(
        [
            "",
            "# Pattern Flow",
            "",
            _normalize_pattern_flow(skill.pattern_flow),
            "",
            "# Usage Instructions",
            "",
            FIXED_USAGE_INSTRUCTIONS,
            "",
            "# Output Guidance",
            "",
            FIXED_OUTPUT_GUIDANCE,
        ]
    )

    return "\n".join(lines).strip()


def _validate_and_normalize_sub_skill(raw_skill: Any, index: int) -> SubSkillData:
    """Validate one sub-skill item and normalize it into a typed record."""
    if not isinstance(raw_skill, dict):
        raise ValueError(f"Item {index} is not an object.")

    name = raw_skill.get("name")
    description = raw_skill.get("description")
    method_program_summary = raw_skill.get("method_program_summary")
    method_program_example = raw_skill.get("method_program_example")
    abstract_action_chain = raw_skill.get("abstract_action_chain")
    source_chunk_ids = raw_skill.get("source_chunk_ids")

    if not isinstance(name, str) or not name.strip():
        raise ValueError("Missing or invalid field: name")
    if not isinstance(description, str) or not description.strip():
        raise ValueError("Missing or invalid field: description")
    if not isinstance(method_program_summary, str):
        raise ValueError("Missing or invalid field: method_program_summary")
    if "method_program_example" not in raw_skill or not isinstance(method_program_example, str):
        raise ValueError("Missing or invalid field: method_program_example")
    if not isinstance(abstract_action_chain, list):
        raise ValueError("Missing or invalid field: abstract_action_chain")
    if not isinstance(source_chunk_ids, list):
        raise ValueError("Missing or invalid field: source_chunk_ids")

    normalized_actions: list[str] = []
    for item in abstract_action_chain:
        if isinstance(item, str) and item.strip():
            normalized_actions.append(item.strip())

    normalized_chunk_ids: list[int] = []
    for item in source_chunk_ids:
        if isinstance(item, int):
            normalized_chunk_ids.append(item)
        else:
            raise ValueError("Invalid field item in source_chunk_ids: must be int")

    return SubSkillData(
        section_id=str(raw_skill.get("section_id", "")).strip(),
        main_skill_id=str(raw_skill.get("main_skill_id", "")).strip(),
        normalized_pattern=str(raw_skill.get("normalized_pattern", "")).strip(),
        name=name.strip(),
        description=description.strip(),
        method_program_summary=method_program_summary.strip(),
        method_program_example=method_program_example.strip(),
        abstract_action_chain=normalized_actions,
        source_chunk_ids=normalized_chunk_ids,
    )


def _render_sub_skill_md(sub_skill: dict[str, Any], index: int) -> str:
    """渲染单个子技能 Markdown。"""
    skill = _validate_and_normalize_sub_skill(sub_skill, index)
    chunk_ids_text = ", ".join(str(item) for item in skill.source_chunk_ids)

    lines = [
        "---",
        f"name: {_yaml_quote(skill.name)}",
        f"type: {_yaml_quote(DEFAULT_SUB_SKILL_TYPE)}",
        f"description: {_yaml_quote(skill.description)}",
        f"section_id: {_yaml_quote(skill.section_id)}",
        f"main_skill_id: {_yaml_quote(skill.main_skill_id)}",
        f"normalized_pattern: {_yaml_quote(skill.normalized_pattern)}",
        f"source_chunk_ids: [{chunk_ids_text}]",
        "---",
        "",
        f"# {skill.name}",
        "",
        "## Description",
        "",
        skill.description,
        "",
        "## Method Program Summary",
        "",
        skill.method_program_summary,
        "",
        "## Method Program Example",
        "",
        skill.method_program_example if skill.method_program_example else "N/A",
        "",
        "## Abstract Action Chain",
        "",
    ]

    if skill.abstract_action_chain:
        for idx, action in enumerate(skill.abstract_action_chain, 1):
            lines.append(f"{idx}. {action}")
    else:
        lines.append("- N/A")

    return "\n".join(lines).strip()


def _sanitize_filename(name: str) -> str:
    """Sanitize a skill name into a Windows-safe markdown filename stem."""
    sanitized = re.sub(r'[<>:"/\\|?*\x00-\x1F]', "_", name)
    sanitized = sanitized.replace(" ", "_")
    sanitized = sanitized.strip().rstrip(". ")
    return sanitized or "unnamed_skill"


def run_render(main_skill_json: dict[str, Any], sub_skill_json: dict[str, Any]) -> dict[str, Any]:
    """渲染主技能与子技能 Markdown 产物。"""
    main_skills = main_skill_json.get("main_skills", [])
    sub_skills = sub_skill_json.get("sub_skills", [])
    if not isinstance(main_skills, list):
        main_skills = []
    if not isinstance(sub_skills, list):
        sub_skills = []

    main_docs: list[str] = []
    for skill in main_skills:
        if not isinstance(skill, dict):
            continue
        main_docs.append(_render_main_skill_md(skill))
    main_skill_md = "\n\n\n".join(main_docs).strip()

    sub_skill_files: list[dict[str, str]] = []
    used_names: set[str] = set()
    for index, skill in enumerate(sub_skills, start=1):
        if not isinstance(skill, dict):
            continue

        rendered = _render_sub_skill_md(skill, index=index)
        safe_name = _sanitize_filename(str(skill.get("name", f"sub_skill_{index}")))
        filename = f"{safe_name}.md"
        counter = 2
        while filename in used_names:
            filename = f"{safe_name}_{counter}.md"
            counter += 1
        used_names.add(filename)

        sub_skill_files.append(
            {
                "name": filename,
                "content": rendered,
            }
        )

    return {
        "main_skill_md": main_skill_md,
        "sub_skill_files": sub_skill_files,
    }