"""校验并读取 main_skill JSON，将其渲染为规范的主技能 Markdown 文档。"""

from __future__ import annotations

import argparse
import json
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any

DEFAULT_INPUT = Path(__file__).resolve().parent / "main_skill_json/main_skill.json"
DEFAULT_OUTPUT_DIR = Path(__file__).resolve().parent / "main_skill_md"
DEFAULT_OUTPUT_FILE = "main_skill.md"
DEFAULT_NAME = "chapter_1"
DEFAULT_TYPE = "main_skill"

FIXED_USAGE_INSTRUCTIONS = """When answering a question with this skill:

- Follow the Method Program as the primary reasoning path.
- Organize the response according to the Execution Skeleton.
- Treat the first step as the evaluative or conceptual baseline.
- Use the middle steps to trace development, identify contradictions, and diagnose internal failure mechanisms.
- Use the final step to connect the internal mechanism to concrete historical or systemic outcomes.
- Do not merely summarize events; explain how transformation or crisis emerges from the system’s own development.
- If a step requires finer expansion, call an appropriate sub-skill."""

FIXED_OUTPUT_GUIDANCE = """Your response should:

- explain the problem as an endogenous process rather than an external accident
- preserve historical and causal continuity
- emphasize the contrast between original principles and later outcomes
- show how internal contradictions generated by prior success lead to crisis, reversal, or transformation"""


@dataclass
class MainSkillData:
    """Store validated main-skill JSON fields for markdown rendering."""

    description: str
    applicability: str
    core_steps: list[str]
    pattern_flow: list[str]
    chapter_method_summary: str
    perspective: str
    perspective_notes: str
    nature: str
    nature_notes: str
    time_orientation: str
    time_orientation_notes: str
    system_scope: str
    system_scope_notes: str
    equilibrium_view: str
    equilibrium_view_notes: str
    logic: list[str]
    logic_notes: str


def parse_args() -> argparse.Namespace:
    """Parse CLI arguments for main-skill markdown generation."""
    parser = argparse.ArgumentParser(description="Render main_skill.json into a guidance-ready main_skill.md.")
    parser.add_argument("--input", type=Path, default=DEFAULT_INPUT, help="Input main_skill JSON file.")
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT_DIR, help="Output markdown directory.")
    parser.add_argument("--output-file", type=str, default=DEFAULT_OUTPUT_FILE, help="Output markdown filename.")
    return parser.parse_args()


def load_input_json(input_path: Path) -> dict[str, Any]:
    """Load and validate the root JSON object."""
    if not input_path.exists():
        raise FileNotFoundError(f"Input file not found: {input_path}")
    data = json.loads(input_path.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise ValueError("Input JSON root must be an object.")
    return data


def require_string(value: Any, field_path: str) -> str:
    """Validate required string field and return a trimmed value."""
    if not isinstance(value, str):
        raise ValueError(f"Missing or invalid field: {field_path} (expected string)")
    text = value.strip()
    if not text:
        raise ValueError(f"Missing or invalid field: {field_path} (empty string)")
    return text


def require_string_list(value: Any, field_path: str) -> list[str]:
    """Validate required list[str] field and return normalized values."""
    if not isinstance(value, list):
        raise ValueError(f"Missing or invalid field: {field_path} (expected list)")
    items: list[str] = []
    for idx, item in enumerate(value):
        if not isinstance(item, str):
            raise ValueError(f"Missing or invalid field: {field_path}[{idx}] (expected string)")
        text = item.strip()
        if not text:
            raise ValueError(f"Missing or invalid field: {field_path}[{idx}] (empty string)")
        items.append(text)
    return items


def validate_and_normalize(data: dict[str, Any]) -> MainSkillData:
    """Validate strict schema and normalize fields for rendering."""
    pattern_summary = data.get("pattern_summary")
    signal_summary = data.get("signal_summary")
    if not isinstance(pattern_summary, dict):
        raise ValueError("Missing or invalid field: pattern_summary")
    if not isinstance(signal_summary, dict):
        raise ValueError("Missing or invalid field: signal_summary")

    required_pattern_keys = [
        "description",
        "applicability",
        "core_steps",
        "pattern_flow",
        "chapter_method_summary",
    ]
    for key in required_pattern_keys:
        if key not in pattern_summary:
            raise ValueError(f"Missing required field: pattern_summary.{key}")

    required_signal_keys = [
        "perspective",
        "nature",
        "time_orientation",
        "system_scope",
        "equilibrium_view",
        "logic",
    ]
    for key in required_signal_keys:
        if key not in signal_summary:
            raise ValueError(f"Missing required field: signal_summary.{key}")

    def read_signal_node(node_key: str) -> tuple[str, str]:
        node = signal_summary.get(node_key)
        if not isinstance(node, dict):
            raise ValueError(f"Missing or invalid field: signal_summary.{node_key}")
        value = require_string(node.get("value"), f"signal_summary.{node_key}.value")
        notes = require_string(node.get("notes"), f"signal_summary.{node_key}.notes")
        return value, notes

    logic_node = signal_summary.get("logic")
    if not isinstance(logic_node, dict):
        raise ValueError("Missing or invalid field: signal_summary.logic")
    logic_values = require_string_list(logic_node.get("value"), "signal_summary.logic.value")
    logic_notes = require_string(logic_node.get("notes"), "signal_summary.logic.notes")

    perspective, perspective_notes = read_signal_node("perspective")
    nature, nature_notes = read_signal_node("nature")
    time_orientation, time_orientation_notes = read_signal_node("time_orientation")
    system_scope, system_scope_notes = read_signal_node("system_scope")
    equilibrium_view, equilibrium_view_notes = read_signal_node("equilibrium_view")

    return MainSkillData(
        description=require_string(pattern_summary.get("description"), "pattern_summary.description"),
        applicability=require_string(pattern_summary.get("applicability"), "pattern_summary.applicability"),
        core_steps=require_string_list(pattern_summary.get("core_steps"), "pattern_summary.core_steps"),
        pattern_flow=require_string_list(pattern_summary.get("pattern_flow"), "pattern_summary.pattern_flow"),
        chapter_method_summary=require_string(
            pattern_summary.get("chapter_method_summary"), "pattern_summary.chapter_method_summary"
        ),
        perspective=perspective,
        perspective_notes=perspective_notes,
        nature=nature,
        nature_notes=nature_notes,
        time_orientation=time_orientation,
        time_orientation_notes=time_orientation_notes,
        system_scope=system_scope,
        system_scope_notes=system_scope_notes,
        equilibrium_view=equilibrium_view,
        equilibrium_view_notes=equilibrium_view_notes,
        logic=logic_values,
        logic_notes=logic_notes,
    )


def yaml_quote(text: str) -> str:
    """Quote text safely for YAML-like frontmatter using JSON string syntax."""
    return json.dumps(text, ensure_ascii=False)


def normalize_pattern_flow(pattern_flow: list[str]) -> str:
    """Render pattern flow into one line; keep single arrow string as-is."""
    if len(pattern_flow) == 1:
        return pattern_flow[0]
    return " -> ".join(pattern_flow)


def render_markdown(skill: MainSkillData) -> str:
    """Render final markdown content from validated main-skill data."""
    lines: list[str] = [
        "---",
        f"name: {yaml_quote(DEFAULT_NAME)}",
        f"type: {yaml_quote(DEFAULT_TYPE)}",
        f"description: {yaml_quote(skill.description)}",
        f"perspective: {yaml_quote(skill.perspective)}",
        f"perspective_notes: {yaml_quote(skill.perspective_notes)}",
        f"nature: {yaml_quote(skill.nature)}",
        f"nature_notes: {yaml_quote(skill.nature_notes)}",
        f"time_orientation: {yaml_quote(skill.time_orientation)}",
        f"time_orientation_notes: {yaml_quote(skill.time_orientation_notes)}",
        f"system_scope: {yaml_quote(skill.system_scope)}",
        f"system_scope_notes: {yaml_quote(skill.system_scope_notes)}",
        f"equilibrium_view: {yaml_quote(skill.equilibrium_view)}",
        f"equilibrium_view_notes: {yaml_quote(skill.equilibrium_view_notes)}",
        "logic:",
    ]

    for item in skill.logic:
        lines.append(f"  - {yaml_quote(item)}")

    lines.extend(
        [
            f"logic_notes: {yaml_quote(skill.logic_notes)}",
            "---",
            "",
            "# Skill Summary",
            "",
            skill.description,
            "",
            "# When to Use",
            "",
            skill.applicability,
            "",
            "# Method Program",
            "",
            skill.chapter_method_summary,
            "",
            "# Execution Skeleton",
            "",
        ]
    )

    for idx, step in enumerate(skill.core_steps, 1):
        lines.append(f"{idx}. {step}")

    lines.extend(
        [
            "",
            "# Pattern Flow",
            "",
            normalize_pattern_flow(skill.pattern_flow),
            "",
            "# Usage Instructions",
            "",
            FIXED_USAGE_INSTRUCTIONS,
            "",
            "# Output Guidance",
            "",
            FIXED_OUTPUT_GUIDANCE,
            "",
        ]
    )
    return "\n".join(lines)


def validate_rendered_markdown(markdown_text: str) -> list[str]:
    """Validate required frontmatter and sections in rendered markdown."""
    issues: list[str] = []
    lines = markdown_text.splitlines()
    if not lines or lines[0].strip() != "---":
        issues.append("Missing frontmatter opening ---")
    else:
        closing_found = any(line.strip() == "---" for line in lines[1:])
        if not closing_found:
            issues.append("Missing frontmatter closing ---")

    required_tokens = [
        'name: "chapter_1"',
        'type: "main_skill"',
        "perspective:",
        "perspective_notes:",
        "nature:",
        "nature_notes:",
        "time_orientation:",
        "time_orientation_notes:",
        "system_scope:",
        "system_scope_notes:",
        "equilibrium_view:",
        "equilibrium_view_notes:",
        "logic:",
        "logic_notes:",
        "# Skill Summary",
        "# When to Use",
        "# Method Program",
        "# Execution Skeleton",
        "# Pattern Flow",
        "# Usage Instructions",
        "# Output Guidance",
    ]
    for token in required_tokens:
        if token not in markdown_text:
            issues.append(f"Missing required content: {token}")
    return issues


def save_markdown(output_path: Path, markdown_text: str) -> None:
    """Save markdown file to output path."""
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(markdown_text, encoding="utf-8")


def print_summary(input_path: Path, output_path: Path, validation_issues: list[str]) -> None:
    """Print concise processing summary and validation status."""
    if validation_issues:
        print("Validation failed.")
        for issue in validation_issues:
            print(f"- {issue}")
    else:
        print("Validation passed.")
    print(f"Input file: {input_path}")
    print(f"Output file: {output_path}")


def main() -> None:
    """Program entry point for main-skill markdown generation."""
    args = parse_args()
    data = load_input_json(args.input)
    skill = validate_and_normalize(data)
    markdown_text = render_markdown(skill)
    issues = validate_rendered_markdown(markdown_text)
    if issues:
        raise ValueError("Rendered markdown validation failed: " + "; ".join(issues))
    output_path = args.output_dir / args.output_file
    save_markdown(output_path, markdown_text)
    print_summary(args.input, output_path, issues)


if __name__ == "__main__":
    try:
        main()
    except Exception as exc:  # pragma: no cover
        print(f"Execution failed: {exc}", file=sys.stderr)
        sys.exit(1)
